services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_broker
